# Ejercicio Determinante

Se realizaron los siguientes cambios en el método *descomposición_LU()*:

1. Pivoteo parcial añadido:

- **Antes:** El código no realizaba ningún tipo de pivoteo.

- **Después:** Se añadió el pivoteo parcial. Ahora se busca la fila con el mayor valor absoluto en la columna actual (*max_row*) y se realiza el intercambio de filas si es necesario.

2. Intercambio de filas en matrices A y L:

- **Antes:** No había intercambios de filas.

- **Después:** Si max_row no coincide con la fila actual (i), se intercambian las filas correspondientes en A y también en las columnas relevantes de L.

3. Condición de singularidad mejorada:

- **Antes:** Solo se verificaba si el pivote actual (A[i, i]) era igual a cero, arrojando un error en ese caso.

- **Después:** Se verifica si el valor máximo en la columna actual (A[max_row, i]) es cero, lo que indica que la matriz es singular y no tiene solución única.

In [6]:
from src.linear_syst_methods import descomposicion_LU

def calcular_determinante_con_LU(A: np.ndarray) -> float:
    """
    Calcula el determinante de una matriz cuadrada utilizando descomposición LU.

    ## Parameters
    ``A``: matriz cuadrada.

    ## Return
    ``det``: determinante de la matriz.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."

    L, U = descomposicion_LU(A)
    det = np.prod(np.diag(U))  # Producto de los elementos de la diagonal de U
    return det

**Calcule el determinante de:**

## Primera matriz

In [3]:
import numpy as np
   
A1 = np.array([
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
    ])

In [7]:
calcular_determinante_con_LU(A1)

[01-23 20:25:12][INFO] 
[[ 5.   5.  -4.   5.  -4.   2.   2.   2.   4.   4. ]
 [ 0.  -1.   4.8  2.   0.8 -2.4  2.6 -0.4  0.2  4.2]
 [ 0.   6.  -7.2  0.  -2.2  3.6  6.6  4.6  8.2  4.2]
 [ 0.   4.   3.2  0.  -4.8  0.4  5.4  0.4  0.8  5.8]
 [ 0.  -3.   7.2 -2.   3.2 -1.6  1.4 -2.6 -3.2 -1.2]
 [ 0.  -4.   2.6 -3.  -0.4 -3.8  1.2 -2.8  2.4 -2.6]
 [ 0.  -5.  -0.6 -5.   1.4 -4.2  3.8 -2.2  2.6 -2.4]
 [ 0.   1.  -0.6  0.   0.4  0.8 -5.2 -5.2 -1.4  2.6]
 [ 0.   4.  -0.2  7.  -6.2 -0.4 -0.4  1.6  8.2 -0.8]
 [ 0.   6.   2.4  0.  -2.6  1.8  5.8 -0.2  4.6 -1.4]]
[01-23 20:25:12][INFO] 
[[ 5.          5.         -4.          5.         -4.          2.
   2.          2.          4.          4.        ]
 [ 0.          6.         -7.2         0.         -2.2         3.6
   6.6         4.6         8.2         4.2       ]
 [ 0.          0.          3.6         2.          0.43333333 -1.8
   3.7         0.36666667  1.56666667  4.9       ]
 [ 0.          0.          8.          0.         -3.33333333 -2.
  

9912776.0

## Segunda matriz

In [8]:
A2 = np.array([
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
    ])


Resolución:

In [9]:
calcular_determinante_con_LU(A2)

[01-23 20:25:50][INFO] 
[[ 5.   4.   0.   3.   4.  -1.  -3.  -2. ]
 [ 0.  -0.2  3.   2.6  1.8  0.8 -4.6  3.6]
 [ 0.   3.4 -3.  -4.2 -3.6  2.4  6.2  3.8]
 [ 0.  -2.4  0.   2.2  0.6  4.6 -5.2 -1.8]
 [ 0.  -2.8 -1.   4.4  4.2  2.2  1.6 -1.6]
 [ 0.   0.4  4.   3.8 -3.6 -2.6  3.2 -1.2]
 [ 0.  -7.2  1.  -0.4 -0.2  3.8  1.4  4.6]
 [ 0.   2.6 -3.   1.2  6.6  3.6  2.8 -4.8]]
[01-23 20:25:50][INFO] 
[[ 5.          4.          0.          3.          4.         -1.
  -3.         -2.        ]
 [ 0.         -7.2         1.         -0.4        -0.2         3.8
   1.4         4.6       ]
 [ 0.          0.         -2.52777778 -4.38888889 -3.69444444  4.19444444
   6.86111111  5.97222222]
 [ 0.          0.         -0.33333333  2.33333333  0.66666667  3.33333333
  -5.66666667 -3.33333333]
 [ 0.          0.         -1.38888889  4.55555556  4.27777778  0.72222222
   1.05555556 -3.38888889]
 [ 0.          0.          4.05555556  3.77777778 -3.61111111 -2.38888889
   3.27777778 -0.94444444]
 [ 0.          0

2341546.0

**GitHub:** git@github.com: alda244



[GitHub Métodos Númericos - Repositorio](https://github.com/alda244/MN_ActividadesExtra/blob/main/PereiraAlicia_ActividadExtra12.ipynb)